# Generated by Django 5.0.4 on 2024-04-10 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_detallepedido_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='valor',
        ),
    ]
