# Generated by Django 5.0.4 on 2024-04-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_detallepedido_valor'),
        ('productos', '0002_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(to='productos.producto'),
        ),
    ]
