# Generated by Django 5.0.4 on 2024-04-10 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_alter_pedido_productos'),
    ]

    operations = [
    ]
