# Generated by Django 5.0.4 on 2024-04-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_auto_20240410_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='valor',
        ),
    ]
